apiVersion: apps/v1
kind: Deployment
metadata:
  name:hapi-nginx-deployment
  labels:
    app: hapi-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi-nginx
  template:
    metadata:
      labels:
        app: hapi-nginx
    spec:
      containers:
        - name: hapi-nginx
          image: acrwdtkhydev.azurecr.io/hapi-nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hapi-nginx-loadbalancer-service
  labels:
    app: hapi-nginx
spec:
  type: LoadBalancer
  selector:
    app: hapi-nginx
  ports:
    - port: 80
      targetPort: 80



